 **1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

**Purpose of NumPy in Scientific Computing and Data Analysis**
NumPy (short for Numerical Python) is a fundamental library in Python that provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing, data analysis, machine learning, and other fields where numerical operations are critical.

**Advantages of NumPy**

1. Efficient Array Operations:

NumPy arrays (ndarrays) are more memory-efficient and faster compared to Python's native lists. They allow for element-wise operations and broadcasting, making it easier to perform complex mathematical computations on large datasets.

2. Support for Multidimensional Arrays:

NumPy supports n-dimensional arrays, making it easy to work with data in multiple dimensions (e.g., 2D matrices, 3D tensors). This is essential for scientific computing and applications like image processing or linear algebra.

3. Performance:

NumPy is implemented in C and Fortran under the hood, allowing it to execute numerical operations much faster than native Python code, which is interpreted.

4. Rich Mathematical Functionality:

It provides a wide range of functions for numerical computing, including linear algebra, Fourier transformations, random number generation, and statistical tools.

5. Broadcasting:

Broadcasting enables arithmetic operations on arrays of different shapes without requiring explicit loops, simplifying the code and improving performance.

6. Interoperability:

NumPy integrates well with other Python libraries like pandas, Matplotlib, and SciPy, forming a strong ecosystem for scientific computing and data analysis.

7. Convenient Data Manipulation:

It offers functionalities for reshaping, slicing, and indexing arrays, making it easy to manipulate and preprocess data.

8. Community and Documentation:

NumPy has extensive documentation, tutorials, and a large, active community, making it beginner-friendly and well-supported.


**How NumPy Enhances Python's Capabilities for Numerical Operations**

1. Array-Oriented Computing:

Python's built-in lists and loops are inefficient for numerical computations. NumPy's ndarrays provide a robust and high-performance data structure designed specifically for numerical data.

2. Vectorized Operations:

NumPy eliminates the need for explicit loops in many cases by performing element-wise operations across entire arrays simultaneously.

3. Integration with C/Fortran:

NumPy allows developers to write performance-critical code in C/Fortran and use it seamlessly in Python, combining high performance with Python's simplicity.

4. Handling Large Datasets:

NumPy is optimized for handling large datasets in memory, which is essential for modern data-intensive applications.

5. Foundation for Other Libraries:

Many popular libraries, such as pandas (data manipulation) and TensorFlow (machine learning), are built on top of NumPy, relying on its efficient array operations as their core.


**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

In NumPy, both np.mean() and np.average() are used to compute the average of an array, but they have distinct functionalities and use cases.

1. np.mean()
Purpose: Calculates the arithmetic mean (simple average) of the elements in an array.

Syntax: np.mean(array, axis=None, dtype=None, keepdims=False)

Key Features:

a. Computes the mean by summing up all elements and dividing by the total number of elements.
b. Operates along a specified axis or on the flattened array if no axis is specified.
c. Does not support weighting (all elements are treated equally).
d. Returns a scalar value for the mean unless keepdims=True is specified.

2. np.average()
Purpose: Calculates a weighted average of the elements in an array.

Syntax:np.average(array, axis=None, weights=None, returned=False)

Key Features:

a. Allows for weighting of elements via the weights parameter.
b. If weights is None, it behaves identically to np.mean().
c. Returns a scalar unless an axis is specified or returned=True is used.
d. The returned=True option adds the sum of weights as a second output.

**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

1. Reversing a 1D Array
For a one-dimensional array, reversing the array essentially reverses the order of its elements.

Method 1: Using slicing
The slicing syntax [::-1] reverses the array:

In [1]:
import numpy as np

# 1D Array
arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]
print("Reversed 1D array (slicing):", reversed_arr)

Reversed 1D array (slicing): [5 4 3 2 1]


Method 2: Using numpy.flip

The numpy.flip function can also reverse a 1D array:

In [2]:
# Reverse using numpy.flip
reversed_arr = np.flip(arr)
print("Reversed 1D array (numpy.flip):", reversed_arr)


Reversed 1D array (numpy.flip): [5 4 3 2 1]


2. Reversing a 2D Array

For two-dimensional arrays, you can reverse elements along specific axes or both axes.

Method 1: Reverse along rows (axis=0)
Reversing along rows means flipping the array vertically:

In [3]:
# 2D Array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows using slicing
reversed_rows = arr[::-1, :]
print("Reversed along rows (slicing):\n", reversed_rows)

# Reverse along rows using numpy.flip
reversed_rows = np.flip(arr, axis=0)
print("Reversed along rows (numpy.flip):\n", reversed_rows)


Reversed along rows (slicing):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along rows (numpy.flip):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Method 2: Reverse along columns (axis=1)

Reversing along columns means flipping the array horizontally:

In [4]:
# Reverse along columns using slicing
reversed_columns = arr[:, ::-1]
print("Reversed along columns (slicing):\n", reversed_columns)

# Reverse along columns using numpy.flip
reversed_columns = np.flip(arr, axis=1)
print("Reversed along columns (numpy.flip):\n", reversed_columns)


Reversed along columns (slicing):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed along columns (numpy.flip):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Method 3: Reverse along both axes

To reverse both axes simultaneously:

In [5]:
# Reverse along both axes using slicing
reversed_both = arr[::-1, ::-1]
print("Reversed along both axes (slicing):\n", reversed_both)

# Reverse along both axes using numpy.flip
reversed_both = np.flip(arr, axis=(0, 1))
print("Reversed along both axes (numpy.flip):\n", reversed_both)


Reversed along both axes (slicing):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reversed along both axes (numpy.flip):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

To determine the data type of elements in a NumPy array, you can use the dtype attribute of the array. For example:

import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3])

# Check the data type of the array
print(array.dtype)

This will output the data type of the array, such as int64, float32, or bool.


Importance of Data Types in Memory Management and Performance

1. Memory Efficiency:

a. NumPy is designed for efficient memory usage. The dtype of an array determines how much memory each element consumes. For instance, an array with int32 elements uses 4 bytes per integer, while an array with float64 elements uses 8 bytes per floating-point number.

b . Choosing the appropriate data type can significantly reduce memory usage, especially for large datasets.

2. Performance:

a. Operations on NumPy arrays are optimized based on their data types. For example, computations on arrays with smaller data types (int8, float32) are faster than on larger data types (int64, float64) because they involve less data movement and fewer CPU cycles.

b. Using the correct data type also helps avoid unnecessary type casting during operations, which can slow down computations.

3. Accuracy:

Some data types, like float32 and float64, differ in precision. Choosing an appropriate type ensures numerical accuracy while balancing memory and performance. For example, float32 might suffice for graphics or simulations, but float64 may be required for scientific calculations where higher precision is needed.

4. Compatibility:

The data type ensures compatibility when interacting with other libraries or systems that expect specific types. For instance, when interfacing with machine learning libraries like TensorFlow or PyTorch, the expected dtype often affects model training performance.

**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

An ndarray (short for n-dimensional array) is the primary data structure in NumPy. It is a grid of values, all of the same data type, indexed by a tuple of non-negative integers. It can represent vectors (1D arrays), matrices (2D arrays), or tensors (n-dimensional arrays).

Key Features of ndarray:

1. Homogeneous Data:

All elements in an ndarray must be of the same data type, ensuring consistency and efficient memory use.

2. N-dimensional Support:

Supports arrays of arbitrary dimensions (1D, 2D, 3D, etc.), enabling operations on complex datasets like images, volumes, and more.

3. Fast and Efficient:

Optimized for numerical computations, leveraging C and Fortran libraries under the hood.
Operations are performed element-wise and are significantly faster than equivalent operations on Python lists.

4. Fixed Size:

Unlike Python lists, ndarrays have a fixed size after creation. Resizing requires creating a new array.

5. Rich Set of Operations:

Supports advanced mathematical operations, broadcasting, slicing, and indexing.
Provides methods for linear algebra, random sampling, Fourier transforms, and more.

6. Memory Efficiency:

Uses contiguous memory blocks and stores data compactly, minimizing overhead compared to Python lists.

7. Data Type Flexibility:

Allows specification of data types (dtype) like int32, float64, or complex128, enabling fine control over memory and performance.


 **6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

NumPy arrays (ndarrays) are significantly faster and more efficient than Python lists for numerical operations due to several key design advantages:

1. Vectorization:
NumPy arrays support vectorized operations, which allow you to apply an operation to the entire array without explicit loops.

This avoids the overhead of Python’s for-loops and makes use of highly optimized C/Fortran-level implementations.

In [8]:
import numpy as np
array = np.array([1, 2, 3, 4])
result = array * 2  # Vectorized multiplication
print(result)


[2 4 6 8]


2. Memory Efficiency:

NumPy arrays use a contiguous block of memory, storing data in a compact and efficient binary format. This minimizes memory overhead compared to Python lists, which store references to individual objects.

In [9]:
import sys
import numpy as np

# Memory usage of a NumPy array
np_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(np_array.nbytes)

# Memory usage of a Python list
py_list = [1, 2, 3, 4, 5]
print(sys.getsizeof(py_list))

20
104


3. Optimized C/Fortran Backend:

NumPy’s backend is implemented in C and Fortran, which are much faster than Python’s interpreted operations.

When performing mathematical operations on arrays, NumPy directly executes compiled code rather than Python bytecode.

4. Avoidance of Type Checking Overhead:

Python lists are heterogeneous, meaning they can hold elements of different types. Every operation involves dynamic type checking, which adds overhead.

NumPy arrays are homogeneous, so operations are streamlined with no type-checking overhead.

5. Broadcasting:

NumPy allows broadcasting, which enables operations on arrays of different shapes without explicitly reshaping or replicating data.

This reduces the need for explicit loops or memory-intensive operations.

In [11]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7 ])
result = array + 10  # Broadcasting
print(result)

[11 12 13 14 15 16 17]


6. Parallelism:

NumPy can leverage multi-threading and parallelism for some operations (e.g., matrix multiplications), whereas Python’s default implementation is single-threaded.

7. Built-in Mathematical Operations:

NumPy provides a wide array of built-in functions (e.g., np.sum, np.mean, np.dot) that are highly optimized for performance.
These functions eliminate the need for implementing numerical algorithms manually.

8. Scalability:

NumPy’s performance advantage becomes more pronounced as the size of the data grows. It is well-suited for handling large-scale datasets, such as in data science, machine learning, or scientific computing.



**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively.

1. vstack():
Stacks arrays vertically (row-wise).
It combines arrays along the vertical (first) axis.
Input arrays must have the same number of columns (shape along axis 1).

In [12]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Vertical stacking
result = np.vstack((array1, array2))
print("vstack result:\n", result)


vstack result:
 [[1 2 3]
 [4 5 6]]


2. hstack():
Stacks arrays horizontally (column-wise).
It combines arrays along the horizontal (second) axis.
Input arrays must have the same number of rows (shape along axis 0).

In [13]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Horizontal stacking
result = np.hstack((array1, array2))
print("hstack result:\n", result)


hstack result:
 [1 2 3 4 5 6]


**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

Both fliplr() and flipud() are array manipulation functions in NumPy that flip arrays along different axes. Below are the differences and details of their behavior:

1. fliplr()

Definition: Stands for "flip left to right". It flips the array horizontally, reversing the order of columns while keeping the rows unchanged.
Applicable Arrays: Only works on arrays with 2 or more dimensions. For 1D arrays, it raises a ValueError.

Effect:

For 2D arrays: The columns are reversed.

For higher-dimensional arrays: The operation is applied to the last axis (axis 1).

Example with a 2D Array:

In [14]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Flip horizontally (reverse columns)
result = np.fliplr(array)
print("Original array:\n", array)
print("fliplr result:\n", result)


Original array:
 [[1 2 3]
 [4 5 6]]
fliplr result:
 [[3 2 1]
 [6 5 4]]


2. flipud()

Definition: Stands for "flip up to down". It flips the array vertically, reversing the order of rows while keeping the columns unchanged.
Applicable Arrays: Works on arrays with 1 or more dimensions.

Effect:

For 1D arrays: The elements are reversed (acts like np.flip()).

For 2D arrays: The rows are reversed.

For higher-dimensional arrays: The operation is applied to the first axis (axis 0).

Example with a 2D Array:

In [15]:
# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Flip vertically (reverse rows)
result = np.flipud(array)
print("Original array:\n", array)
print("flipud result:\n", result)


Original array:
 [[1 2 3]
 [4 5 6]]
flipud result:
 [[4 5 6]
 [1 2 3]]


**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

The numpy.array_split() method is used to split an array into multiple sub-arrays. It is similar to numpy.split() but with the key advantage that it can handle uneven splits gracefully, making it more flexible.

Key Features of array_split():

1. Splits Along an Axis:

You can specify the axis along which to split the array (default is axis 0).

2. Handles Uneven Splits:

Unlike numpy.split(), which raises an error if the array cannot be split evenly, array_split() distributes the extra elements among the first few sub-arrays.

3. Returns Sub-Arrays:

The method returns a list of ndarray objects representing the sub-arrays.

Syntax: numpy.array_split(array, indices_or_sections, axis=0)

a. array: The input array to split.

b. indices_or_sections: Specifies how to split the array:

If an integer n is provided, the array is divided into n sub-arrays (evenly or unevenly).

If a sequence (list or array) of indices is provided, the array is split at the specified positions.

c. axis: The axis along which the array is split (default is 0).

Handling Uneven Splits:

When the array cannot be evenly divided into the specified number of sub-arrays, array_split() allocates the extra elements to the earlier sub-arrays, ensuring all sub-arrays are as balanced as possible.

Examples:
1. Splitting a 1D Array Evenly:

In [16]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
result = np.array_split(array, 3)
print("Result:", result)


Result: [array([1, 2]), array([3, 4]), array([5, 6])]


**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

Both vectorization and broadcasting are powerful concepts in NumPy that contribute significantly to its efficiency and performance in array operations. They help eliminate the need for explicit loops, enabling faster computations and more readable code.

1. Vectorization

Definition:

Vectorization is the process of applying operations directly on entire arrays (or "vectors") instead of using explicit loops to iterate over individual elements. It leverages NumPy's internal optimizations, which are implemented in C, to perform operations efficiently.

Key Features:
a. Eliminates the need for Python for loops.
b. Improves code readability and reduces boilerplate code.
c. Operations are performed at compiled speeds (in C), making them much faster than standard Python loops.

Example:

Without Vectorization (Using Loops):


In [17]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise addition using a loop
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])

print("Result without vectorization:", result)


Result without vectorization: [6, 8, 10, 12]


2. Broadcasting

Definition:

Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes and sizes by "stretching" smaller arrays to match the dimensions of the larger array without copying data.

Rules of Broadcasting:

a. If the arrays differ in the number of dimensions, the smaller array is padded with extra dimensions (of size 1) on the left until the shapes match.

b. If the shape of one array is 1 along a dimension, it is "stretched" to match the size of the other array along that dimension.

c. If the sizes along a dimension do not match and neither is 1, broadcasting raises an error.

Key Features:
1. Enables operations between arrays of different shapes.
2. Avoids unnecessary memory usage by not replicating smaller arrays.
3. Simplifies array computations by automatically handling shape mismatches.

Examples of Broadcasting:

Example 1: Scalar and Array:

In [18]:
import numpy as np

# Add a scalar to an array
a = np.array([1, 2, 3])
result = a + 5
print("Broadcasting scalar to array:", result)


Broadcasting scalar to array: [6 7 8]


In [19]:
#Example 2: Arrays with Different Shapes:

# Create two arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Add two arrays
result = a + b
print("Broadcasting arrays of different shapes:\n", result)



Broadcasting arrays of different shapes:
 [[11 22 33]
 [14 25 36]]


In [20]:
#Example 3: Higher-Dimensional Arrays:

# Create two arrays
a = np.array([[[1], [2], [3]]])  # Shape (1, 3, 1)
b = np.array([[10, 20]])         # Shape (1, 2)

# Add arrays
result = a + b
print("Broadcasting higher-dimensional arrays:\n", result)


Broadcasting higher-dimensional arrays:
 [[[11 21]
  [12 22]
  [13 23]]]


**Practical Questions:**

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**


In [22]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array.T

print("Original Array:")
print(array)

print("\nTransposed Array:")
print(transposed_array)



Original Array:
[[34 87 12]
 [79 21 94]
 [10 86 94]]

Transposed Array:
[[34 79 10]
 [87 21 86]
 [12 94 94]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**


In [25]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)

# Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("Original 1D Array:")
print(array_1d)

print("\nReshaped to 2x5 Array:")
print(array_2x5)

print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**


In [26]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:")
print(array_4x4)

print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.89948454 0.55802868 0.70711554 0.10375457]
 [0.70504609 0.35577204 0.39371272 0.40986445]
 [0.80337574 0.30053233 0.12220258 0.88390093]
 [0.32885106 0.83222178 0.04034263 0.35701531]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.89948454 0.55802868 0.70711554 0.10375457 0.        ]
 [0.         0.70504609 0.35577204 0.39371272 0.40986445 0.        ]
 [0.         0.80337574 0.30053233 0.12220258 0.88390093 0.        ]
 [0.         0.32885106 0.83222178 0.04034263 0.35701531 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**


In [27]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element**

In [28]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

print("Original Array:")
print(array)

print("\nUppercase Transformation:")
print(uppercase_array)

print("\nLowercase Transformation:")
print(lowercase_array)

print("\nTitle Case Transformation:")
print(titlecase_array)

print("\nCapitalize Transformation:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**


In [29]:
import numpy as np

# Generate a NumPy array of words
array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word in the array
array_with_spaces = np.array([' '.join(word) for word in array])

print("Original Array:")
print(array)

print("\nArray with Space Between Characters:")
print(array_with_spaces)


Original Array:
['python' 'numpy' 'pandas']

Array with Space Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**


In [30]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**


In [31]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

In [32]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("Array of 100 random integers:")
print(random_array)

print("\nPrime numbers in the array:")
print(prime_numbers)


Array of 100 random integers:
[ 248   79  558  879  530  875  109  868  538  355  489  390  633   82
  946  452  795  145  223  119  410   81  967  446   93 1000  444  975
  472  133  970  904  576  256  737  625  483  160  867  833  547  601
  533  993  728  240  957  220  670  975  830  410  908  771  949  569
  634  431  287  701  564  353  436   37  820   37  969  840  153  948
  904  184  988  115  613  550   96  756  815  775  470  548  570  321
  168    9  205   56  441   88  628  948  484  936  645  478  448  572
  580  649]

Prime numbers in the array:
[79, 109, 223, 967, 547, 601, 569, 431, 701, 353, 37, 37, 613]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages**

In [37]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Random temperatures between 15 and 35 degrees Celsius


weekly_temperatures = daily_temperatures.reshape(30, 1)


weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Temperatures ( months x days):")
print(weekly_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[16 24 18 32 22 21 31 21 31 24 17 32 15 34 19 30 30 16 23 34 30 18 33 22
 20 33 20 21 25 20]

Weekly Temperatures ( months x days):
[[16]
 [24]
 [18]
 [32]
 [22]
 [21]
 [31]
 [21]
 [31]
 [24]
 [17]
 [32]
 [15]
 [34]
 [19]
 [30]
 [30]
 [16]
 [23]
 [34]
 [30]
 [18]
 [33]
 [22]
 [20]
 [33]
 [20]
 [21]
 [25]
 [20]]

Weekly Averages:
[16. 24. 18. 32. 22. 21. 31. 21. 31. 24. 17. 32. 15. 34. 19. 30. 30. 16.
 23. 34. 30. 18. 33. 22. 20. 33. 20. 21. 25. 20.]
